# Generated by Django 4.1.1 on 2022-10-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('FechaReserva', models.DateField()),
                ('horaReserva', models.TimeField()),
                ('CantidadPersonas', models.IntegerField()),
                ('Estado', models.CharField(max_length=10)),
                ('Observacion', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('donante', models.BooleanField()),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
