# Generated by Django 4.1.3 on 2022-12-22 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigocategoria', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigoproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('codigoBarra', models.IntegerField()),
                ('codigocategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.categoria')),
            ],
        ),
    ]
